brand/urls.py
from django.urls import path
from .views import IndexPage


app_name = 'brand'

urlpatterns = [
    path('', IndexPage.as_view(), name='home')
]

head_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brand.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brand/models.py
from django.core.validators import RegexValidator
from django.db import models
from ckeditor.fields import RichTextField
from django.db.models import TextField


class Header(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    text = models.TextField(max_length=500, verbose_name='Текст')
    button_text = models.CharField(max_length=255, verbose_name='Текст кнопки')
    button_link = models.URLField(max_length=255, verbose_name='Ссылка кнопки')
    image = models.ImageField(upload_to='header_images/', verbose_name='Фото')

    class Meta:
        verbose_name_plural = 'Header Info'

    def __str__(self):
        return f'Header Info'


class Service(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    description = models.TextField(max_length=500, verbose_name='Описание')
    order = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True, verbose_name='Доступно/Недоступно')

    class Meta:
        verbose_name_plural = 'Services'
        ordering = ('order', )

    def __str__(self):
        return f'{self.title}'


class Portfolio(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    post = models.CharField(max_length=255, verbose_name='Должность')
    image = models.ImageField(upload_to='portfolio_images/', verbose_name='Фото')
    order = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True, verbose_name='Доступно/Недоступно')

    class Meta:
        verbose_name_plural = 'Portfolio Items'
        ordering = ('order', )

    def __str__(self):
        return f'{self.title}'


class About(models.Model):
    date = models.CharField(max_length=255, verbose_name='Дата')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    description = models.TextField(max_length=750, verbose_name='Описание')
    image = models.ImageField(upload_to='about_images/', verbose_name='Фото')
    order = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True, verbose_name='Доступно/Недоступно')

    class Meta:
        verbose_name_plural = 'About Items'
        ordering = ('order', )

    def __str__(self):
        return f'{self.date}'


class Team(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя')
    post = models.CharField(max_length=255, verbose_name='Должность')
    twitter = models.URLField(max_length=255, verbose_name='Twitter')
    facebook = models.URLField(max_length=255, verbose_name='Facebook')
    linkedin = models.URLField(max_length=255, verbose_name='LinkedIn')
    image = models.ImageField(upload_to='team_images/', verbose_name='Фото')
    order = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True, verbose_name='Доступно/Недоступно')

    class Meta:
        verbose_name_plural = 'Team Items'
        ordering = ('order', )

    def __str__(self):
        return f'{self.name}'


class Client(models.Model):
    company = models.CharField(max_length=255, verbose_name='Компания')
    image = models.ImageField(upload_to='client_images/', verbose_name='Фото')
    order = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True, verbose_name='Доступно/Недоступно')
    link = models.URLField(max_length=255, verbose_name='Ссылка')

    class Meta:
        verbose_name_plural = 'Client Items'
        ordering = ('order', )

    def __str__(self):
        return f'{self.company}'


class Footer(models.Model):
    copyright_text = RichTextField()
    twitter = models.URLField(max_length=255, verbose_name='Twitter')
    facebook = models.URLField(max_length=255, verbose_name='Facebook')
    linkedin = models.URLField(max_length=255, verbose_name='LinkedIn')
    privacy_police = models.URLField(max_length=255, verbose_name='Privacy Policy')
    tou = models.URLField(max_length=255, verbose_name='Terms of Use')

    class Meta:
        verbose_name_plural = 'Footer Items'

    def __str__(self):
        return f'Footer Items'


class ContactUs(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    email = models.EmailField(verbose_name='Почта')
    phone_regex = RegexValidator(regex=r'^\+?\d{7,12}$',
                                 message='Phone number should be in format: +380xxxxxxxxx')
    phone = models.CharField(validators=[phone_regex, ], max_length=20, verbose_name='Номер телефона')
    message = models.TextField(max_length=500, verbose_name='Сообщение', blank=True)
    is_precessed = models.BooleanField(default=False, verbose_name='Обработано')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обработано')

    class Meta:
        ordering = ('-created_at', )
        verbose_name_plural = 'Contact Us'

    def __str__(self):
        return f'{self.name} - {self.phone}'


class MainItems(models.Model):
    services_title = models.CharField(max_length=100, verbose_name='Services Title')
    portfolio_title = models.CharField(max_length=100, verbose_name='Portfolio Title')
    about_title = models.CharField(max_length=100, verbose_name='About Title')
    team_title = models.CharField(max_length=100, verbose_name='Team Title')
    team_description = models.TextField(max_length=500, verbose_name='Team Description')
    contact_title = models.CharField(max_length=100, verbose_name='Contact Title')

    class Meta:
        verbose_name_plural = 'Main Site Items'

    def __str__(self):
        return f'Main Site Items'


class PortfolioModal(models.Model):
    name = models.CharField(max_length=100, verbose_name='Project Name', unique=True)
    title = models.CharField(max_length=150, verbose_name='Project Title', blank=True)
    image = models.ImageField(upload_to='portfolio_modal_images/', verbose_name='Фото')
    description = models.TextField(max_length=500, verbose_name='Project Description')
    client = models.CharField(max_length=100, verbose_name='Client')
    category = models.CharField(max_length=100, verbose_name='Category')
    is_visible = models.BooleanField(default=True, verbose_name='Доступно/Недоступно')
    order = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = 'Portfolio Modals'
        ordering = ('order', )

    def __str__(self):
        return f'{self.name}'

brand/forms.py
from django import forms
from .models import ContactUs


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(label='Name',
                           widget=forms.TextInput(attrs={
                               'class': 'form-control',
                               'placeholder': 'Your Name',
                               'data-rule': 'minlen: 3',
                               'data-msg': 'Please enter at least 3 chars',
                           }))
    email = forms.EmailField(label='email',
                             widget=forms.EmailInput(attrs={
                                 'placeholder': 'Your Email',
                                 'class': 'form-control',
                                 'id': 'email',
                                 'data-rule': 'email',
                                 'data-msg': 'Please enter a valid email',
                             }))

    phone = forms.CharField(label='phone',
                            widget=forms.TextInput(attrs={
                                'placeholder': 'Your Phone',
                                'class': 'form-control',
                                'id': 'phone',
                                'data-rule': 'minlen:4',
                                'data-msg': 'Please enter a valid phone: 0xxxxxxxxx',
                            }))

    message = forms.CharField(label='message',
                              widget=forms.Textarea(attrs={
                                  'placeholder': 'Message',
                                  'class': 'form-control',
                                  'rows': '5',
                              }))

    class Meta:
        model = ContactUs
        fields = ('name', 'email', 'phone', 'message')

brand/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import Header, Service, Portfolio, About, Team, Client, Footer, MainItems, PortfolioModal
from .forms import ContactUsForm


class IndexPage(TemplateView):
    template_name = 'brand_main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        headers = Header.objects.all()
        services = Service.objects.filter(is_visible=True)
        portfolios = Portfolio.objects.filter(is_visible=True)
        abouts = About.objects.filter(is_visible=True)
        teams = Team.objects.filter(is_visible=True)
        clients = Client.objects.filter(is_visible=True)
        footers = Footer.objects.all()
        main_items = MainItems.objects.all()
        modals = PortfolioModal.objects.filter(is_visible=True)
        context['headers'] = headers
        context['services'] = services
        context['portfolios'] = portfolios
        context['abouts'] = abouts
        context['teams'] = teams
        context['clients'] = clients
        context['footers'] = footers
        context['main_items'] = main_items
        context['modals'] = modals
        return context

    def post(self, *args, **kwargs):
        contact_form = ContactUsForm(self.request.POST)

        if contact_form.is_valid():
            contact_form.save()
            messages.success(self.request, 'Contact done')
            return redirect('/')

        context = self.get_context_data()
        context['contact_form'] = contact_form
        messages.error(self.request, 'Error in form Contact Us')
        return render(self.request, self.template_name, context=context)

brand/templates/about.html
<!-- About-->
<section class="page-section" id="about">
    <div class="container">
    {% for main_item in main_items %}
        <div class="text-center">
            <h2 class="section-heading text-uppercase">About</h2>
            <h3 class="section-subheading text-muted">{{ main_item.about_title }}</h3>
        </div>
    {% endfor %}
        <ul class="timeline">
            {% for about in abouts %}
                {% if forloop.counter|divisibleby:2 %}
                    {# Если индекс делится на 2 без остатка, значит, это четный индекс #}
                    <li class="timeline-inverted">
                {% else %}
                    {# Иначе это нечетный индекс #}
                    <li>
                {% endif %}
                    <div class="timeline-image"><img class="rounded-circle img-fluid" src="{{ about.image.url }}" alt="..." /></div>
                    <div class="timeline-panel">
                        <div class="timeline-heading">
                            <h4>{{ about.date }}</h4>
                            <h4 class="subheading">{{ about.title }}</h4>
                        </div>
                        <div class="timeline-body"><p class="text-muted">{{ about.description }}</p></div>
                    </div>
                </li>
            {% endfor %}
            <li class="timeline-inverted">
                <div class="timeline-image">
                    <h4>Be Part<br/>Of Our<br/>Story!</h4>
                </div>
            </li>
        </ul>
    </div>
</section>

brand/templates/brand_main.html
{% extends 'index.html' %}

{% block content %}
    {% include 'head.html' %}
    {% include 'services.html' %}
    {% include 'portfolio.html' %}
    {% include 'about.html' %}
    {% include 'team.html' %}
    {% include 'clients.html' %}
    {% include 'contact.html' %}
{% endblock %}

brand/templates/clients.html
<!-- Clients-->
<div class="py-5">
    <div class="container">

            <div class="row align-items-center">
                {% for client in clients %}
                <div class="col-md-3 col-sm-6 my-3">
                    <a href="{{ client.link }}"><img class="img-fluid img-brand d-block mx-auto" src="{{ client.image.url }}" alt="..." aria-label="Microsoft Logo" /></a>
                </div>
                {% endfor %}
            </div>

    </div>
</div>

brand/templates/contact.html
<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">CONTACT US</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>

        <form method="post" action="{% url 'brand:home' %}" id="contactForm">
            {% csrf_token %}

            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" name="name" type="text" placeholder="Ваше имя" required />
                    </div>
                    <div class="form-group">
                        <input class="form-control" name="email" type="email" placeholder="Ваш Email" required />
                    </div>
                    <div class="form-group mb-md-0">
                        <input class="form-control" name="phone" type="tel" placeholder="Ваш телефон" required />
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        <textarea class="form-control" name="message" placeholder="Ваше сообщение" required></textarea>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>
            </div>
        </form>
    </div>
</section>

brand/templates/head.html
<!-- Masthead-->

{% for header in headers %}
<header class="masthead" style="background-image:url('{{ header.image.url }}');">
    <div class="container">
        <div class="masthead-subheading">{{ header.title }}</div>
        <div class="masthead-heading text-uppercase">{{ header.text }}</div>
        <a class="btn btn-primary btn-xl text-uppercase" href="#services">{{ header.button_text }}</a>
    </div>
</header>

{% endfor %}

brand/templates/portfolio.html
<!-- Portfolio Grid-->
<section class="page-section bg-light" id="portfolio">
    <div class="container">
        {% for main_item in main_items %}
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Portfolio</h2>
                <h3 class="section-subheading text-muted">{{ main_item.portfolio_title }}</h3>
            </div>
        {% endfor %}
        <div class="row">
            {% for portfolio in portfolios %}
                <div class="col-lg-4 col-sm-6 mb-4">
                    <!-- Portfolio item -->
                    <div class="portfolio-item">

                        <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal{{ portfolio.id }}">
                            <div class="portfolio-hover">
                                <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="{{ portfolio.image.url }}" alt="..." />
                        </a>
                        <div class="portfolio-caption">
                            <div class="portfolio-caption-heading">{{ portfolio.title }}</div>
                            <div class="portfolio-caption-subheading text-muted">{{ portfolio.post }}</div>
                        </div>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <!-- Portfolio Modals-->
    {% for modal in modals %}
        <div class="portfolio-modal modal fade" id="portfolioModal{{ modal.id }}" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="/static/assets/img/close-icon.svg" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">{{ modal.name }}</h2>
                                    <p class="item-intro text-muted">{{ modal.title }}</p>
                                    <img class="img-fluid d-block mx-auto" src="{{ modal.image.url }}" alt="..." />
                                    <p>{{ modal.description }}</p>
                                    <ul class="list-inline">
                                        <li>
                                            <strong>Client:</strong>
                                            {{ modal.client }}
                                        </li>
                                        <li>
                                            <strong>Category:</strong>
                                            {{ modal.category }}
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="fas fa-xmark me-1"></i>
                                        Close Project
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</section>

brand/templates/services.html
<!-- Services-->
<section class="page-section" id="services">
    <div class="container">
    {% for main_item in main_items %}
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Services</h2>
            <h3 class="section-subheading text-muted">{{ main_item.services_title }}</h3>
        </div>
    {% endfor %}

            <div class="row text-center">
                {% for service in services %}
                    <div class="col-md-4">
                        <span class="fa-stack fa-4x">
                            <i class="fas fa-circle fa-stack-2x text-primary"></i>
                            <i class="fas fa-shopping-cart fa-stack-1x fa-inverse"></i>
                        </span>
                        <h4 class="my-3">{{ service.title }}</h4>
                        <p class="text-muted">{{ service.description }}</p>
                    </div>
                {% endfor %}
            </div>
    </div>
</section>

brand/templates/team.html
<!-- Team-->
<section class="page-section bg-light" id="team">
    <div class="container">
    {% for main_item in main_items %}
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
            <h3 class="section-subheading text-muted">{{ main_item.team_title }}</h3>
        </div>
    {% endfor %}
            <div class="row">
                {% for team in teams %}
                    <div class="col-lg-4">

                            <div class="team-member">
                                <img class="mx-auto rounded-circle" src="{{ team.image.url }}" alt="..." />
                                <h4>{{ team.name }}</h4>
                                <p class="text-muted">{{ team.post }}</p>
                                <a class="btn btn-dark btn-social mx-2" href="{{ team.twitter }}" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-dark btn-social mx-2" href="{{ team.facebook }}" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-dark btn-social mx-2" href="{{ team.linkedin }}" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                            </div>
                    </div>
                {% endfor %}
            </div>
        {% for main_item in main_items %}
            <div class="row">
                <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">{{ main_item.team_description }}</p></div>
            </div>
        {% endfor %}
    </div>
</section>